#!/bin/bash
#User Options
EDITOR=vi
PATCH_REPO=/home/dave/dev/sysfilerepo/
# WARNING: Do NOT use ~ or $HOME in the patch repo, as they will change undesirably
# if/when you launch this process as sudo

#Check preliminary conditions
#argument supplied?
if [[ -z $1 ]]; then
	echo "Usage: sysedit <filename>"
	exit 1
fi

#file supplied exists?
if [[ ! -e "$1" ]]; then
	echo "Error opening '$1' - Please check path and filename"
	exit 1
fi

#Do we have write permissions? If not, ask for sudo login
if [[ ! -w $1 ]]; then
	sudo -s $0 "$1"
	exit 0
fi

#if we got here, we passed inspection. definitions:
BACKUP_FILE="$1.orig"
PATCH_FILE=$1`date +%Y%m%d-%s`.patch

# Make a backup!
cp "$1" "$BACKUP_FILE"

# Open the file with our editor of choice
$EDITOR $1

# Make a patch file based on our edits
diff $BACKUP_FILE $1 > $PATCH_FILE

# diff will return 0 if no changes were made, 1 if changes WERE made
if [[ $? -eq 0 ]]; then  #no changes, clean up and exit
	rm $PATCH_FILE
	rm $BACKUP_FILE
	echo "sysedit: No changes made to `basename $1`"
	exit 0
fi

#If we're here, changes were made. Save them to the repo, clean up, and exit
if [ ! -d $PATCH_REPO ]; then
	mkdir -p $PATCH_REPO
fi

mv $PATCH_FILE $PATCH_REPO

echo "sysedit: `basename $1` updated. Changes saved as $PATCH_REPO$PATCH_FILE"

