#!/bin/bash
# Fetches a random lyric from the Sonata built lyric database in ~/.lyrics.
# Filters out any blank line and attempts to filter lines starting with punctuation or blank space
sourcedir=~/.lyrics

line=""
while [[ -z $line ]] || [[ -z $(echo $line | sed -e "s/^[\ \/\'\<\{\(]//g") ]]; do
  file=${sourcedir}/$(ls $sourcedir | shuf -n1)
  num=$(( RANDOM % $(< "$file" | wc -l) + 1))
  line=$(head -${num} "$file" | tail -1)
done

echo $line | sed -e 's/[\(\<\>\)\{\}]//g' #final filter
