#!/bin/bash

shopt -s extglob

MAXLEN=50

mpd() {
  socat - tcp-connect:localhost:6600 <<< "$*"
}

while IFS=':' read attr val; do
  case "$attr" in
    Artist|Title) declare "${attr,,}=${val:1}" ;;
  esac
done < <(mpd "currentsong")

[[ $artist && $title ]] && printf -v track '%s - %s' "$artist" "$title"

if (( ${#track} > MAXLEN )); then
  track=${track:0:MAXLEN}
  track=${track% *}...
fi

printf "[ %s ] " "${track:-off the air}"

