#!/bin/bash

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias clearflags='unset CFLAGS CPPFLAGS LDFLAGS'
alias getflags='unset CPPFLAGS; eval $(sed -rn "s/^((C|LD|MAKE)FLAGS)/export \1/p" /etc/makepkg.conf)'
alias grep='grep --color'
alias info='info --vi-keys'
alias j='jobs'
alias lla='ls -la'
alias ls='ls --group-directories-first --color'
alias md5='md5sum'
alias nj='ninja -C build'
alias sdu='systemctl --user'
alias sudo='sudo '
alias v='vim'
alias wtc="curl --silent 'http://whatthecommit.com/index.txt'"
